[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CEVILOG ImageViewer"
version = "0.0.1"
authors = [
  { name="Frédéric Gabel", email="frederic@cevilog.com" },
]
description = "Image viewer based UI built in PythonQt5"
readme = "README.md"
requires-python = ">=3.11.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Windows 10",
]
